apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - nodePort: 30200
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  
