apiVersion: v1
kind: ReplicationController
metadata:
  name: web
spec:
  replicas: 10
  template:
    metadata:
      labels:
        env: test
        app: frontend
    spec:
      containers:
      - name: site1
        image: nginx
