apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: testing
spec:
  selector:
   matchLabels:
    app: web
    tier: fend
  replicas: 5
  template:
    metadata:
     labels:
       app: web
       tier: fend
    spec:
      containers:
        - name: web
          image:  nginx
