apiVersion: v1
kind: ReplicaSet
metadata:
  name: testing
spec:
  replicas: 7
  templates:
    metadata:
     labels:
       app: web
       tier: fend
    spec:
      containers:
        - name: web
          image:  nginx