apiVersion: v1
kind: Service
metadata:
 name: web-app-cip
spec:
 type: ClusterIP #it's default, Evern if we are not mentioning it will use cluster ip by default
 ports:
 - targetPort: 80 #Application port number inside pod
   port: 80 #PortNumber used with domain name or ip   EX- V.W.X.Y:80
 selector:  #Traffic from service will be routed to below label 
  app: web
  tier: fend
