apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: NodePort
  ports:
  -  targetPort: 80 #Application port number on pod level
     port: 80 #ClusterIP portnumber -> NodePort ip request sent internally to clusterip
     nodePort: 30000
  selector:
    app: web


